#!/usr/bin/env bash
# TODO: a full installation like:
# https://github.com/makerdao/mcd-cli/blob/master/install.sh
export PATH=$PATH:/`pwd`/bin

# Load environment with sensible data
if [ -f .env ]
then
  export $(cat .env | xargs)
else
  echo "Please, add a .env as described in the README file"
  exit 1
fi


function debug() {
	hevm exec \
     --caller $(seth tx $1 from) \
     --address $(seth tx $1 to) \
     --calldata $(seth tx $1 input) \
     --rpc $ETH_RPC_URL \
     --block $(($(seth tx $1 blockNumber)-1)) \
     --gas $(seth tx $1 gas) \
     --debug
}

# Use these functions to switch the seth environment
function fuse() {
  export ETH_RPC_URL=https://rpc.fuse.io
  export ETH_KEYSTORE=./keys
  export ETH_GAS=10000000
  export ETH_GAS_PRICE=1000
  export ETH_PASSWORD=./keys/PASS-ALL
}

function kovan() {
  export ETH_RPC_URL=$NET_ETH_KOVAN
  export ETH_KEYSTORE=./keys
  export ETH_GAS=10000000
  export ETH_GAS_PRICE=1
  export ETH_PASSWORD=./keys/PASS-ALL
}

function testnet-local() {
  export ETH_RPC_URL=http://127.0.0.1:9545
  export ETH_KEYSTORE=./keys
  export ETH_GAS=10000000
  export ETH_GAS_PRICE=1
  export ETH_PASSWORD=./keys/PASS-ALL
}

function optimism-local() {
  export ETH_RPC_URL=http://127.0.0.1:8545
  export ETH_KEYSTORE=./keys
  export ETH_GAS=10000000
  export ETH_GAS_PRICE=1
  export ETH_PASSWORD=./keys/PASS-ALL
}
