#!/usr/bin/env bash
set -e


seth balance $Deployer2
# /**                                                                                    
# * @dev Performs the logic for withdrawals by burning the token and informing          
# *      the L1 token Gateway of the withdrawal.                                        
# * @param _l2Token Address of L2 token where withdrawal is initiated.                  
# * @param _from Account to pull the withdrawal from on L2.                             
# * @param _to Account to give the withdrawal to on L1.                                 
# * @param _amount Amount of the token to withdraw.                                     
# * @param _l1Gas Unused, but included for potential forward compatibility consideration
# * @param _data Optional data to forward to L1. This data is provided                  
# *        solely as a convenience for external contracts. Aside from enforcing a max.
# *        length, these contracts provide no guarantees about its content.             
# */
# code: L2/messaging/L2StandardBridge.sol
# function withdraw(address _l2Token,uint256 _amount,uint32 _l1Gas, bytes calldata _data
seth send $L2_STANDARD_BRIDGE \
  --from $Deployer2 \
  "withdraw(address,uint256,uint32,bytes)" $OVM_ETH "1000" "1" $(seth --to-bytes32 "5")
seth balance $Deployer2






